sudo: required
dist: trusty
language: java
jdk:
- oraclejdk8
services:
- mongodb
branches:
  only:
  - develop
  - master
cache:
  directories:
  - $HOME/.m2
notifications:
  email:
    recipients:
    - cedar-core-developers@lists.stanford.edu
    on_success: never
    on_failure: always
before_install:
- sleep 15
- mongoimport --db cedar --collection users --file cedar-terminology-server-application/src/test/resources/test-user-1.json
install: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -DskipTests=true clean deploy
  --settings .m2/travis-settings.xml'
env:
  global:
  - CEDAR_ADMIN_USER_UUID=abc
  - CEDAR_ADMIN_USER_PASSWORD=abc
  - CEDAR_NEO4J_TRANSACTION_URL=abc
  - CEDAR_NEO4J_AUTH_STRING=abc
  - CEDAR_NEO4J_AUTH_STRING=abc
  - CEDAR_HOST=abc
  - CEDAR_HOME=abc
  - CEDAR_TEST_USER2_UUID=abc
  - CEDAR_TEST_USER3_UUID=abc
  - CEDAR_ADMIN_USER_API_KEY=abc
  - CEDAR_NCBI_SRA_FTP_PASSWORD=abc
  - secure: TDXqUXpR3G5DIFQpQ8Ne2wQsj17P/G6wU2agw3ssSSuqCUIadOHwGFW8PD8Ffe1frQCq6axLouEGnnh+9hPxwIhr+kqZytwzP5lPJOxowwzhd1q6Z38hmLlBg6bKE/XwPTzZQhPUx0O5//pPCYHEE1HkB3dwIVN91Rro0Xy74Izb2RHuBUdC6ToOIzkJ9mleoozZFUbx0X2IdkrXgOc9bo+a9QfiKxHhpR3krhsie/CMHmZ032fZk7y2X5/hvKaqaXTo5XJj3lecxy5sLld/XK63lynih7ouCE7iiRTgobIPXM5cg/jexfaWwiCHoYat7Aq94nnlVwte+yXuxfAYUjLugcvVouDJ8fNodaxwrA+2QOsMJNOOBbmHCbqHJ8uwEQLtQYbzdqPPa9f63ObR5S1mJxgxRsXboqVCNNb4zvKm3c+5iAXd8xu0xdl/M/nEHEylrsel+pQfuPNXAvRNkgiEV+37wS1N77iwcnUMxuTMCBmUOcnw0V03SbmSHTrrpDEaUboEEiP+GYLIKgLySPE+TU/tE/lNGtCyUSu1vWeK4iaB/MkgRYzeFKrFoT//S83Q1hj/Mf0qTz9gOOIP66yfD2SDOhsd2d2FLILHB12ix9+1+7CYUUTuUSHa/djEogj17iJeag/QnMTRfNSonpfaVp79o4R80aggPR+IODg=
  - secure: a0xhJa+SWdsmyMVUofamTj54HH1x/6sq4JvWIjZdLR3XFNuT/OQHBTOcxX/kHMmNdCReI17AfY2pJcDgPWO/9n1r+NSjeEirLozrcoi/ObPwFZ5aJane5glc7YFYEeyKd32LNjqZXZcxMRaQNm+PchMm2kcNs1mxMTTq3hzadit6cY/NEgyH3fYaouVGbqCp/fkmKPAXHh9HCt0iOQnNTT89gGpJ/AC0Cl2Sp0PMazzkIDt5/F1BN7LBPimYI39Xd47Ylidwf5egUrY5wIcJ3DV+m6Cw0uTT2mGpYP776drjON+o0ZRowxuLJotXhBSH9QAR/k4FTQkOcktsyUES6IqHwHeF4RJodBYZ5pSQSOiNglbf0KhFPOpTd8F6iq5K33bm+6C2Oc2/6GAgs/EiwdkQEhATwolZbi9ExGIrIwpAWoAz/uHuFAEo5/v4rB392TuHMMA8YzeFi444B5+CQYKXzOn/aaA+m3u5b+9qFaz3aH49vgsnF9kCFhUIUqkK/VbM3eqp+QBDchuh0UohcxvdZTidQgG+uRgRd8OXYPUu3j/BvITWYlbbEZ1g2/RQlNtSRFu0sJAu67N8nrBVzUbdSBNQdVh55fafIdQi/Rkngw/dWc2akqlSVJpNjIJX5EaKuJAuvAjFI/tWEy1ECLrPqyjnF6Eqrx6tzcweAG4=
  - secure: uzagKDE0jk+LPvaVolf0jEQ00kCo5hUiik8ip0XOpqwrdJcw8/k6Qbl+MWVe4GciALDfj09WVlAX4a7Rghr5vPNQqudxZ1vnoR/2JX0b19FSJ7me6RioODliA1ZVXS0zPNqZZQnJGFyMOOqWUZOeyjSPDyrgvTgIjqGfU1ouSpPYW+ImwHSKwKpGRLuqwYqlLmDj8MVPFgktwf11kdMqMk1RlRiIdOxTrikX7SGBlh4U8Q8JLdEAgfgV5XZpO/oGXX2SD8oUlB33tNQe5JAL5WRrZ76Fbcgwo64hK77XUAqJue31tD9FWiQbec3sJBMSphH1P/w8q6+u9n+QXKeyAqs2DaXHi1dvmXq2Dm5WBkPDChYg7CN1Ed0R6SoR6Zx89qB5lTk2BInrjkP7/HGa6AKzGU8AZfdGed3vSO0y7i8DK8NkukFZXnCqBBBFUuQH7oMWIzsPsVXprzRmBmx5cTN5GcS4Ppq3U2Q2QuvjyVnWG07Ely8DYRlJ9/bsOU0bU9/7tlF2rsrJNFYAfzdklBWZkMeNjHtJZXXr0mT6UfRjWr58K81/m8WxEm8SNLReGeqlPnZ8LQYYhrczqHy7JFzGqZh5zhz21IOJ3FoPw65CxKHjtT2J9gXbAJQzaetjuIEQPTjBP8tOP4P97+RPmKLsfq/st14HUF1XK8xGAoQ=
