sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
services:
  - mongodb
branches:
  only:
  - develop
  - master
cache:
  directories:
  - $HOME/.m2
notifications:
  email:
    recipients:
    - cedar-core-developers@lists.stanford.edu
    on_success: never
    on_failure: always
before_script:
  - sleep 15
  - mongoimport --db cedar --collection users --file cedar-terminology-server-application/src/test/resources/test-user-1.json
install: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn clean deploy --settings .m2/travis-settings.xml'
env:
  global:
  - secure: D7QFbMlUlIyTxCbtBQg/IHn+tg1KTE4y1aB2pp0ueC1zv3S07YQpDg0tm0922nqH+PFeI8VD/fsUQlZjhlw3BTt5rBtAbo1gQ0CiEpeIa8rOmSKFX9ZeaZMNAxHAOcsxWLPAQy04dV9sZdiBJ45Vc+hfEXMKxFBDZYzvtyrUoILEbl7Hyxd2OmO8z9h3grm5TV2P0yMfY5yNb+hPoxxMiiN9duHFGJ5LzM3F5h2muDamr7qOpktlpgWWLwJTSP779RZ4h/jfaBySFE5ugMj6k0fw7RdRpp14yTgzDcSQ42e4120zgunPONPel7cAEKb6jOpGAZ91lPzMweCIo2wq6vY2pZYU4bjl2aA7UIgD0hjhGG+pNKoqNaGY3lPyM6Tnw3GDyXHlQAmIqAcqvYcMx5QAmrRkpIf/x/WA/gyDeH/TOgd3IxmrGUq9ogNaVxayuT9y8nxhcvFNSFLxoOhFZbJU/+FSpw4d0+pttvpsSaCEF7Y/qlIGSYsZu5EAr7hV+JfJDfWGPl2hwDo2pcDK3lPWSmPiW1yOv5zx/8S+kwOMviFe2u5NFmNhiaoi4JIsnCBlPjPNcD2xqJmquobaUy/cRvPNA/tHHyocAl8YmDXJy7meASWZfKDu9ZPjWDIj/28V0JFoCQE/J53JCDAmd7Cc2cVzRRJKpVhc7GHHdYI=
  - secure: qIMLoi4wgJd2IQi2MfwHy3iAewVxFqtd2k59aQ3+hDrEpwi0+1n5+OfPC6R0X9b3z1DAm5bSHLje1yBmv5mpKQ7HvowComCwKfnpbhNw1iGMNWhmzXS8k4sDB1uF1lkQjokxng9uI/Wn8rRlz24rJjGS9FlJ2wrZ+/rEdtSVrQwWIO6GrA9j8iyyZTvBzC45OsGoHFO83Bl8mIh7try0SRFVc8PrPG9eRFWVVPHAEg9sCAqQfPN3w5WIiPsF+pEkXRn7NzDHPSH0WPlVSsLbfJ3c0UNVP1Dwu57fW/YdFhzS66Rm5PUVH1eLlmHlhhzkdgXSWK8ajeqwGgh9Q0MQIoV4cwrHbQwioesr80FXF0DrRSljipyclqyqqQZSBMb6fLTUPRDFEm9InNeD+gjENqVODbKViFALhimOObc/q9FjfN10GIfFt6kinlW0CrQy6osvDy55nPpJuLhra7NbBG28ld20ijZ2lnHOZXaxaDul8V5E7aLcr1/LOsRErnypt5Y5bIKk516p6nL9DPHyf2GQA1Ijzz6lKobcupRFyve5LnWWq0kFvqqoYHy2bCo5sIPCbCz8qWyBa/EXJgm7d4zmNmDpdljQNm1+yd9eCoyI5lVwqmgm7MZbKZ976jFXTcwKkTdyad5Tt1sSAK27jx6lEMg8I3VbjzoSvYvVFps=
  - secure: l8gPV902swpnU1Dw4GNp7/ARe6IxYXlEsd3a3V3kG9aPH+0w5u7f86kvTUWBOxom2FgBCCxGpeF/zmJUIbLzaq0513JwXuA8+xshleVQ6Ug8iNqeVyZRajN//oRjl2+wlkXjFo42sXmcmx58MEItKbBHkukXznsA1gcALdvNNwZ0XIvP0KKQBDoEvKKvG+ZqeN+9Lb6GqNVh/EHxdwIJQKWJO+uRi8C9IrN69j5hkEx4PlZFglqzuWDcG+GP+hRZ/mO6JEBAGuAP1TaXEjwOqPvR0lUyG0x7+9He46qY3Qf1dyrwD9p9KFSyrJySLCu9TXXxtrGLQSbMjTxxTz/lTrjEfJmjbeJjxJ5PINiNaGXRzO5DrfEPvI97haL1MoYNH/MquWOZVYAGJnRSj6Ochebt7RA9zimxJb8hzRd0mThYPIt1CUcAJxaXTe2HcuNR67yhQwuS9R3byRZ4Db+Qe5B5vRJE77feM1fw/G9bwrAlFdZmrTI6TBsuLA7ZU2uwKRBxCtd9xaP9B5oT6FkH7F4DfYguVRnHvfhY2wXyxAuuNNw7fjgQD4jgX2fcagHMK4V3x8dfd8gmfbsFLLsZQ/Ev4t+gGAJFYhic7/FIgwbhmxD1mIJLKLZCjl5YbSph8IUQN9scmyxTlL+o002T7fiKLm7y71l4xBos2IZJ2j4=
  - secure: v5lt5+SkuMy5n4QYUShcw2FT9ZoLgZL8TfoC8/pE322VMkVOzsn6AsKOCX4nDwzLOSvxMylu1U4+kJ+KGzsQTN7j8Vzk177fFgHD/c/TjLKC++VECRsjhKJE2Ax39v85vb4ZyjXljPEIy0ei4U8MrS7m5EeuriQi0DzOlVKuyM3xiqjahVlrPiCZleQreGpvKHKumHSbWyWfOxT3NMzkDg5SJnwairbJn6d1IAvnqKkH9jSOxNcGdTnZeaiZU7DB12/b47U4t2DLUQeUXrtFg7VLw87aI6mXNbWggBa26WsKxO1HKC73kLhnTySNZj9NRaknBn8//BqclHAKW5gWq/l49ifzvQBkIWUDuo8ONgRXdLLwthGfT0mnNqOXsWTDLgJV2KQ54XAAiTBisRyXb7R/j8b0LWJ24455IuGCh0nr5dZ9suflmk54rfXcCw8uSnGK38FdfpfaIGRyzzJaiZ45FGxm4y9bOW6LTSO8z86d4oYIqLVY7Sy4+bxY0dqOXZVZ4Wm4abBxhMugz+puOOIO9OsWwMeHP3G1WF6tIm/6dYVGcn52qEz3BhNni/AXpPfdv3Cukl7hd+jt4YuQDiGjoD6HppDioYGvlw3/LhGKWNSAYoJx9a1GQMX7mM+nvjqzXboNeJhJPYT10jOP6kb9q78vxcei/2ldLvkdbU8=
  - CEDAR_ADMIN_USER_UUID=abc
  - CEDAR_ADMIN_USER_PASSWORD=abc
  - CEDAR_NEO4J_TRANSACTION_URL=abc
  - CEDAR_NEO4J_AUTH_STRING=abc
  - CEDAR_NEO4J_AUTH_STRING=abc
  - CEDAR_HOST=abc
  - CEDAR_HOME=abc
  - CEDAR_TEST_USER2_UUID=abc
  - CEDAR_TEST_USER3_UUID=abc