sudo: required
dist: trusty
language: java
jdk:
- oraclejdk8
services:
- mongodb
branches:
  only:
  - develop
  - master
notifications:
  email:
    recipients:
    - cedar-core-developers@lists.stanford.edu
    on_success: never
    on_failure: always

before_install:
  - sleep 15
  - mongoimport --db cedar --collection users --file cedar-terminology-server-application/src/test/resources/test-user-1.json  
  - mongo cedar --eval "db.createUser( { user:'fred', pwd:'fred', roles:[ 'readWrite'] })"

install: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -DskipTests=false clean deploy --settings .m2/travis-settings.xml'

script: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -DskipTests=true clean --settings .m2/travis-settings.xml'

env:
  global:
  - CEDAR_HOME=${HOME}/
  - CEDAR_HOST=abc
  - CEDAR_MONGO_USER_NAME=fred
  - CEDAR_MONGO_USER_PASSWORD=fred
  - CEDAR_LD_USER_BASE=https://metadatacenter.org/users/
  - CEDAR_TEST_USER1_ID=https://metadatacenter.org/users/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
  - CEDAR_TEST_USER2_ID=abc
  - CEDAR_ADMIN_USER_UUID=abc
  - CEDAR_ADMIN_USER_PASSWORD=abc
  - CEDAR_NEO4J_TRANSACTION_URL=abc
  - CEDAR_NEO4J_AUTH_STRING=abc
  - CEDAR_SALT_API_KEY=fred
  - CEDAR_ADMIN_USER_API_KEY=abc
  - CEDAR_NCBI_SRA_FTP_PASSWORD=abc
  - secure: a0xhJa+SWdsmyMVUofamTj54HH1x/6sq4JvWIjZdLR3XFNuT/OQHBTOcxX/kHMmNdCReI17AfY2pJcDgPWO/9n1r+NSjeEirLozrcoi/ObPwFZ5aJane5glc7YFYEeyKd32LNjqZXZcxMRaQNm+PchMm2kcNs1mxMTTq3hzadit6cY/NEgyH3fYaouVGbqCp/fkmKPAXHh9HCt0iOQnNTT89gGpJ/AC0Cl2Sp0PMazzkIDt5/F1BN7LBPimYI39Xd47Ylidwf5egUrY5wIcJ3DV+m6Cw0uTT2mGpYP776drjON+o0ZRowxuLJotXhBSH9QAR/k4FTQkOcktsyUES6IqHwHeF4RJodBYZ5pSQSOiNglbf0KhFPOpTd8F6iq5K33bm+6C2Oc2/6GAgs/EiwdkQEhATwolZbi9ExGIrIwpAWoAz/uHuFAEo5/v4rB392TuHMMA8YzeFi444B5+CQYKXzOn/aaA+m3u5b+9qFaz3aH49vgsnF9kCFhUIUqkK/VbM3eqp+QBDchuh0UohcxvdZTidQgG+uRgRd8OXYPUu3j/BvITWYlbbEZ1g2/RQlNtSRFu0sJAu67N8nrBVzUbdSBNQdVh55fafIdQi/Rkngw/dWc2akqlSVJpNjIJX5EaKuJAuvAjFI/tWEy1ECLrPqyjnF6Eqrx6tzcweAG4=
  - secure: uzagKDE0jk+LPvaVolf0jEQ00kCo5hUiik8ip0XOpqwrdJcw8/k6Qbl+MWVe4GciALDfj09WVlAX4a7Rghr5vPNQqudxZ1vnoR/2JX0b19FSJ7me6RioODliA1ZVXS0zPNqZZQnJGFyMOOqWUZOeyjSPDyrgvTgIjqGfU1ouSpPYW+ImwHSKwKpGRLuqwYqlLmDj8MVPFgktwf11kdMqMk1RlRiIdOxTrikX7SGBlh4U8Q8JLdEAgfgV5XZpO/oGXX2SD8oUlB33tNQe5JAL5WRrZ76Fbcgwo64hK77XUAqJue31tD9FWiQbec3sJBMSphH1P/w8q6+u9n+QXKeyAqs2DaXHi1dvmXq2Dm5WBkPDChYg7CN1Ed0R6SoR6Zx89qB5lTk2BInrjkP7/HGa6AKzGU8AZfdGed3vSO0y7i8DK8NkukFZXnCqBBBFUuQH7oMWIzsPsVXprzRmBmx5cTN5GcS4Ppq3U2Q2QuvjyVnWG07Ely8DYRlJ9/bsOU0bU9/7tlF2rsrJNFYAfzdklBWZkMeNjHtJZXXr0mT6UfRjWr58K81/m8WxEm8SNLReGeqlPnZ8LQYYhrczqHy7JFzGqZh5zhz21IOJ3FoPw65CxKHjtT2J9gXbAJQzaetjuIEQPTjBP8tOP4P97+RPmKLsfq/st14HUF1XK8xGAoQ=
  - secure: Jp6lSZpjSnpf3guoAeeVxD/6rTWVzh3afAz3UZoOuGYswdAVW008D2tRqRKbBuoZguF3HLy+LThHUDFLmt8kQqaGouQwC8J+vCIbrRvdwetABU33xlsibXcQgXLV97W3jIiLexBC4CfWZkCOm5L+EaF71KMyPgfaDQo0jfeHwUeto3Gueq9M2taHp89EGrzk+KKgS4zXugXZqOoO7f27avNixFJoJEoYUV3P5WghpcxTYcPJOnIhFw5p3hU49pu4/BEtcc7JOUpxNOQplF882SCKF91KmMIcL+O8G0W6SJ4A1lhECXJSKr6V/7XgLh3PTEnTYzjrduS8qVFaM+yHMIa3qMSohA+l2jNirpkjJ5vDJaxNYG2JcsDWX/a9Ok37+G5vPNjDdscGkRNQ1ul/rkWLTojhNFvF6clcLP8Tjk0zn7jrKi8ZTraJceRk6qnWb+a9bzSBV02ZF0UxTlD7stro8Vngazo9N+cCxbuLxIXQSSUDRulA11v54GlgPnY5VQ4lWzr3PrR2pMS989EtUAH7EfQ5EMMiOWqvtPaW9kb6uS/JIPeGYBAjs9Wd/hp5t5a6tECAeMd7weDEYAlnDI91ZoUSQ5mPPHZjPVSeYDwfufJB/GNPlbJo0kFo/Zali6e1lO9XPnKgBnBWpyHdKiui1ZxfMLNI6wy1rjowWu4=
